### ISSUE TITLE
Move the wallet db from BDB to a database maintained under a permissive license

### ISSUE THREAD

**Issue by fokep** [BTCPrivate/archived-full-node-wallet#19]
I thought this had been fixed long time ago upstream in Zcash but apparently it is now becoming technical debt and I think this also should be listed as an issue for BTCP now that we have "active development".

Unknown to what I'm talking about? Do `file wallet.dat` and then `db_dump -l wallet.dat`

Then do `dnf info libdb` or whatever is equivalent in your distro and look at which version you have. 

And do you know WHY you don't have a compatible version (6.x.x)? It's because Oracle decided to change their license

[Changes between 12.1.6.0.19 and 12.1.6.0.20
Updated LICENSE file to reflect change to AGPL. [#22590]](http://download.oracle.com/otndocs/products/berkeleydb/html/changelog_6_0.html)

Issue is basically a duplicate of [this](https://github.com/zcash/zcash/issues/1469). [Related](https://github.com/zcash/zcash/issues/2410)

**Comment by ch4ot1c** [comment]
We have plans to move toward the BTC codebase in general; this will come along the way. Thank you for pointing it out.
