### ISSUE TITLE
Error bitcoin private full node wallet on Mac 

### ISSUE THREAD

**Issue by ootisra** [BTCPrivate/archived-full-node-wallet#26]
This is the message when trying to launch the Bitcoin Private Full node wallet:

an unexpected critical error has occurred: com.eclipsesource.json.ParseException: Expected value at 1:1 See console output for more detailed error information!

I have a Macbook pro Os 10.11.6 El Capitan

**Comment by Pega88** [comment]
can you upload (last part of) the logs? Should be in
~/Library/Application Support/BTCPrivate/
under 'debug.log'

**Comment by ootisra** [comment]
I was able to go to the directory ~/Library/Application Support/BTCPrivate
and found only 1 file btcprivate.conf but could not find the debug.log

**Comment by Pega88** [comment]
is that file empty? what if you restart the wallet, does that directory get filled then?

**Comment by lipepalomares111** [comment]
Same error after restoring BTCPrivate.7z data.

Debug.log
https://pastebin.com/yZg3Cqas
* there's no sensitive data here, right?

@Pega88

**Comment by lipepalomares111** [comment]
+1

**Comment by ch4ot1c** [comment]
Please update your client; this is from the old zcash params url being removed.

**Comment by lucianocn** [comment]
Same error here with latest version. I downloaded 1.0.1 from releases but says 1.0.0 on header.
<img width="879" alt="screen shot 2018-03-04 at 21 28 03" src="https://user-images.githubusercontent.com/3828136/36952825-72f5f324-1ff3-11e8-9a95-8c27be7f975b.png">

Log:
https://pastebin.com/abF45c8D

@ch4ot1c @Pega88

**Comment by Santhosh114** [comment]
Same here and I had to upgrade since the destinations addresses starting with b1 was not identified by version 1.0.0., Everything summed up in the screenshot:
<img width="1036" alt="screen shot 2018-03-04 at 5 11 47 pm" src="https://user-images.githubusercontent.com/14152628/36953411-503b6766-1fcf-11e8-80b0-f785a31a46bc.png">
