### ISSUE TITLE
Restoring blockchain from Archive with backed up wallet.dat error

### ISSUE THREAD

**Issue by VERTlG0** [BTCPrivate/archived-full-node-wallet#40]
Following this https://support.btcprivate.org/561209-Why-wont-the-Full-Node-Desktop-Wallet-sync-past-98-99 that was posted from twitter I backed up my wallet.dat.. removed all files except wallet.dat, and btcprivate.conf as stated. downloaded the new blockchain archive.. moved over the two directories . copied over my wallet.dat backup to .btcprivate/ re-ran ./src/btcpd. Run wallet. and it shows. 0.00 and my addresses are gone!! Please tell me I can retrieve those funds. 

Running btcpd with my backed up wallet.dat produces " Messages: ---Error:  Init message: Verifying wallet... " and seems to create a wallet.bak file so when it shows my 0.00 balance in the wallet. its running the newly created wallet. dat.

**Comment by fokep** [comment]
Is the blockchain completely synced?

**Comment by VERTlG0** [comment]
running the node causes and error when verify wallet.. running wallet without node letting it start the btcpd on its own also causes error:

> z170x ~/cryptomining/wallets/btcp/bitcoin-private-full-node-wallet # java -jar build/jars/BitcoinPrivateDesktopWallet.jar
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Bitcoin Private Full-Node Desktop Wallet (GUI, made in Java & Swing) 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] OS: Linux = LINUX 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Current directory: /root/cryptomining/wallets/btcp/bitcoin-private-full-node-wallet 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Class path: build/jars/BitcoinPrivateDesktopWallet.jar 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Environment PATH: /sbin:/bin:/usr/sbin:/usr/bin 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Available look and feel: Metal javax.swing.plaf.metal.MetalLookAndFeel 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Available look and feel: Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel 
> [main] [Wed Mar 07 13:07:49 EST 2018] [INFO] Setting look and feel: javax.swing.plaf.nimbus.NimbusLookAndFeel 
> [main] [Wed Mar 07 13:07:50 EST 2018] [INFO] Using Bitcoin Private daemon and rpc tools: btcpd: /root/cryptomining/wallets/btcp/bitcoin-private-full-node-wallet/build/jars/btcpd, btcp-cli: /root/cryptomining/wallets/btcp/bitcoin-private-full-node-wallet/build/jars/btcp-cli 
> [main] [Wed Mar 07 13:07:50 EST 2018] [INFO] btcpd is not running at the moment or has not started/synchronized 100% - showing splash... 
> [main] [Wed Mar 07 13:07:50 EST 2018] [INFO] Splash: checking if btcpd is already running... 
> [main] [Wed Mar 07 13:07:50 EST 2018] [INFO] Splash: btcpd will be started... 
> [main] [Wed Mar 07 13:07:59 EST 2018] [ERROR] Unexpected error:  
> java.io.IOException: error: couldn't connect to server: unknown (code -1)
> (make sure server is running and you are connecting to the correct RPC port)
> 	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:173)
> 	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
> 	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:633)

**Comment by VERTlG0** [comment]
When running the standalone node after adding the blockchain archive dirs blocks and chainstate, to the .btcprivate dir with btcprivate.conf and wallet.dat backup, this is the output:

> 
> Since starting this node 1 seconds ago:
> - You have validated no transactions.
> 
> Messages:
> - Error:
> 
> Init message: Verifying wallet...
> 
> [Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> btcpd: /root/cryptomining/coins/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
> Aborted

**Comment by fokep** [comment]
Per the [Troubleshooting guide](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/blob/master/docs/TroubleshootingGuide.md) the error below can indicate blockchain corruption and can be possibly be fixed by running `btcpd -noindex`. Could you try that and see if you can get the btcpd running first?

`java.io.IOException: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)`

**Comment by VERTlG0** [comment]
running btcpd -noindex returns 

> 
> Thank you for running a Bitcoin Private node!
> You're helping to strengthen the network and contributing to a social good :)
> 
> In order to ensure you are adequately protecting your privacy when using
> Bitcoin Private, please see <https://z.cash/support/security/index.html>.
> 
> Since starting this node 0 seconds ago:
> - You have validated no transactions.
> 
> Messages:
> - Error:
> 
> Init message: Verifying wallet...
> 
> [Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> z170x ~/cryptomining/coins/BitcoinPrivate #

**Comment by fokep** [comment]
Oops, typo. Should be `btcpd -reindex`, not `noindex` :-)

**Comment by fokep** [comment]
Oops, typo. Should be `btcpd -reindex`! Not `btcpd -noindex`. Sorry :-)

**Comment by VERTlG0** [comment]
It's ok. -reindex returned the mutex error. 

> Thank you for running a Bitcoin Private node!
> You're helping to strengthen the network and contributing to a social good :)
> 
> In order to ensure you are adequately protecting your privacy when using
> Bitcoin Private, please see <https://z.cash/support/security/index.html>.
> 
> Since starting this node 0 seconds ago:
> - You have validated no transactions.
> 
> Messages:
> - Error:
> 
> Init message: Verifying wallet...
> 
> [Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> btcpd: /root/cryptomining/coins/BitcoinPrivate/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
> Aborted

**Comment by VERTlG0** [comment]
Possibly a clue in db.log 

> 
> BDB2506 file unknown has LSN 1/640434, past end of log at 1/28
> BDB2507 Commonly caused by moving a database from one database environment
> BDB2508 to another without clearing the database LSNs, or by removing all of
> BDB2509 the log files from a database environment
> BDB0522 Page 0: metadata page corrupted
> BDB0523 Page 0: could not check metadata page
> wallet.dat: BDB0090 DB_VERIFY_BAD: Database verification failed
> BDB2506 file unknown has LSN 1/640434, past end of log at 1/1076
> BDB2507 Commonly caused by moving a database from one database environment
> BDB2508 to another without clearing the database LSNs, or by removing all of
> BDB2509 the log files from a database environment
> wallet.1520456835.bak: BDB0090 DB_VERIFY_BAD: Database verification failed

**Comment by VERTlG0** [comment]
The debug.log is saying salvage found no records in my wallet.dat file.. Something is right because I know thats the correct wallet.dat file that I backed up from checking my bash history. Theres records on it so salvage isnt working properly or the file got corrupted somehow.. if thats the case. Im going to run a scrub on my drive which will find it if its been corrupted and restore it.

**Comment by VERTlG0** [comment]
BTW I already classify this account as gone... luckily I didnt have much in it compared to others who are mining.. I just want to confirm its good as gone or that is recoverable.. and fix it so it doesnt occur again. All I did was made a copy of wallet.dat..  which wasnt good enough.. Perhaps I shouldve made two copies.. but then again it depends on what the issue is.. perhaps no backup of wallet.dat will work.  Im currently trying to find others who experienced the wallet syncing crash issue to see if they had success with their backed up wallet.dat files

**Comment by ch4ot1c** [comment]
Sorry to hear this. I had a support request where we were able to recover funds from a wallet.bak; the daemon code uses file locks, so it didn't send without it saving the address into the wallet file. The instructions do say that you need to back up wallet.dat each time you make a new Z address, since they dont come from a deterministic key-chain.
