### ISSUE TITLE
no connection, while using bitcoin-private-full-node-wallet

### ISSUE THREAD

**Issue by agent-0007** [BTCPrivate/archived-full-node-wallet#42]
I have a problem - zero connection (no nodes), I have already visited 
https://www.masternode.link/
and generate btcprivate.conf file:

addnode=btcp.masternode.link
addnode=dnsseed.btcprivate.org
addnode=masternode.link

But still have 0 connection in status.

**Comment by adiadore** [comment]
had this issue after importing the blockchain dump, deleting everything and downloading the blockchain via the node worked for me

**Comment by agent-0007** [comment]
ok, thx for you answer. Now i try download blockchain dump, but speed is very low(
