### ISSUE TITLE
EOF Reached (Code1) - Windows

### ISSUE THREAD

**Issue by runningwithbeer** [BTCPrivate/archived-full-node-wallet#9]
I downloaded the blockchain and put it in c:\users\ %username%\%appdata%\roaming\BTCPrivate but I just get this error every time...

Couldn't connect to server: EOF Reached (Code1)

**Comment by fokep** [comment]
Getting this as well. https://imgur.com/a/cJtPX

**Comment by ch4ot1c** [comment]
I've gotten this too. @fokep Let us know how that goes.

**Comment by ch4ot1c** [comment]
#7 #22
